import * as THREE from 'three';

export const WEATHERS = {
  dawn: {
    skyTop:      new THREE.Color(0x1a0533),
    skyBot:      new THREE.Color(0xe85a2b),
    fogColor:    new THREE.Color(0xdd8855),
    fogNear:     60,
    fogFar:      350,
    ambientInt:  0.5,
    sunInt:      1.0,
    sunColor:    new THREE.Color(0xffaa55),
    sunDir:      new THREE.Vector3(0.0, 0.15, -1.0).normalize(),
    sunGlow:     new THREE.Color(0xff9944),
    sunGlowSize: 0.75,
    windStrength: 0.3,
    turbulence:   0.0,
    cloudOpacity: 0.65,
    cloudTint:    new THREE.Color(0xffcc88),
    oceanColor:   new THREE.Color(0x1a3555),
    oceanSpec:    new THREE.Color(0xff9955),
    islandColor:  new THREE.Color(0x3d6b2e),
    rain:        false,
    turbidity:   8,
    rayleigh:    0.8,
    mieCoefficient: 0.04,
    exposure:    0.38,
    bloomStrength: 0.4,
    bloomThreshold: 0.5,
  },
  day: {
    skyTop:      new THREE.Color(0x4a8fc9),
    skyBot:      new THREE.Color(0x99cbe8), // warmer, brighter near-horizon blue
    fogColor:    new THREE.Color(0xb7dff2),
    fogNear:     180,
    fogFar:      4200,
    ambientInt:  0.45,
    sunInt:      0.95,
    sunColor:    new THREE.Color(0xfff5e6),
    sunDir:      new THREE.Vector3(0.3, 0.8, -0.5).normalize(),
    sunGlow:     new THREE.Color(0xffeedd),
    sunGlowSize: 0.5,
    windStrength: 0.2,
    turbulence:   0.0,
    cloudOpacity: 0.88,
    cloudTint:    new THREE.Color(0xffffff),
    oceanColor:   new THREE.Color(0x0e7ab5),
    oceanSpec:    new THREE.Color(0xffffff),
    islandColor:  new THREE.Color(0x2d5a27),
    rain:        false,
    turbidity:   3,
    rayleigh:    1,
    mieCoefficient: 0.005,
    exposure:    0.52,
    bloomStrength: 0.18,
    bloomThreshold: 0.88,
  },
  dusk: {
    skyTop:      new THREE.Color(0x0d0221),
    skyBot:      new THREE.Color(0xff4500),
    fogColor:    new THREE.Color(0xff7733),
    fogNear:     50,
    fogFar:      280,
    ambientInt:  0.45,
    sunInt:      1.2,
    sunColor:    new THREE.Color(0xff6633),
    sunDir:      new THREE.Vector3(-0.1, 0.1, -1.0).normalize(),
    sunGlow:     new THREE.Color(0xff5522),
    sunGlowSize: 1.2,
    windStrength: 0.4,
    turbulence:   0.0,
    cloudOpacity: 0.75,
    cloudTint:    new THREE.Color(0xff8855),
    oceanColor:   new THREE.Color(0x1a2040),
    oceanSpec:    new THREE.Color(0xff6622),
    islandColor:  new THREE.Color(0x4a3520),
    rain:        false,
    turbidity:   12,
    rayleigh:    0.5,
    mieCoefficient: 0.06,
    exposure:    0.35,
    bloomStrength: 0.8,
    bloomThreshold: 0.25,
  },
  night: {
    skyTop:      new THREE.Color(0x0c0c18),
    skyBot:      new THREE.Color(0x252a45),
    fogColor:    new THREE.Color(0x1e2640),
    fogNear:     400,
    fogFar:      4500,
    ambientInt:  0.38,
    sunInt:      0.5,
    sunColor:    new THREE.Color(0x8899aa),
    sunDir:      new THREE.Vector3(0.5, 0.5, -0.5).normalize(),
    sunGlow:     new THREE.Color(0x8899bb),
    sunGlowSize: 0.4,
    windStrength: 0.15,
    turbulence:   0.0,
    cloudOpacity: 0.15,
    rain:        false,
    cloudTint:    new THREE.Color(0x2a2a40),
    oceanColor:   new THREE.Color(0x0f1628),
    oceanSpec:    new THREE.Color(0x446688),
    islandColor:  new THREE.Color(0x0e1218),
    turbidity:   0.5,
    rayleigh:    0.2,
    mieCoefficient: 0.002,
    exposure:    0.45,
    bloomStrength: 0.15,
    bloomThreshold: 0.88,
  },
  storm: {
    skyTop:      new THREE.Color(0x1a1c28),
    skyBot:      new THREE.Color(0x2a2e40),
    fogColor:    new THREE.Color(0x222838),
    fogNear:     80,
    fogFar:      650,
    ambientInt:  0.35,
    sunInt:      0.35,
    sunColor:    new THREE.Color(0x556688),
    sunDir:      new THREE.Vector3(0.15, 0.25, -0.85).normalize(),
    sunGlow:     new THREE.Color(0x334455),
    sunGlowSize: 0.0,
    windStrength: 3.2,
    turbulence:   1.2,
    cloudOpacity: 0.92,
    rain:        true,
    cloudTint:    new THREE.Color(0x3a3d50),
    oceanColor:   new THREE.Color(0x0a1420),
    oceanSpec:    new THREE.Color(0x445566),
    islandColor:  new THREE.Color(0x1a2520),
    turbidity:   18,
    rayleigh:    0.35,
    mieCoefficient: 0.1,
    exposure:    0.32,
    bloomStrength: 0.12,
    bloomThreshold: 0.96,
  },
};

// Lerp between two weather presets (for smooth transitions)
export function lerpWeather(a, b, t) {
  const lerp = (x, y) => x + (y - x) * t;
  const lerpC = (ca, cb) => ca.clone().lerp(cb, t);
  const lerpV = (va, vb) => va.clone().lerp(vb, t).normalize();
  return {
    skyTop:       lerpC(a.skyTop,    b.skyTop),
    skyBot:       lerpC(a.skyBot,    b.skyBot),
    fogColor:     lerpC(a.fogColor,  b.fogColor),
    fogNear:      lerp(a.fogNear,    b.fogNear),
    fogFar:       lerp(a.fogFar,     b.fogFar),
    ambientInt:   lerp(a.ambientInt, b.ambientInt),
    sunInt:       lerp(a.sunInt,     b.sunInt),
    sunColor:     lerpC(a.sunColor,  b.sunColor),
    sunDir:       lerpV(a.sunDir,    b.sunDir),
    sunGlow:      lerpC(a.sunGlow,   b.sunGlow),
    sunGlowSize:  lerp(a.sunGlowSize, b.sunGlowSize),
    windStrength: lerp(a.windStrength, b.windStrength),
    turbulence:   lerp(a.turbulence,   b.turbulence),
    cloudOpacity: lerp(a.cloudOpacity, b.cloudOpacity),
    cloudTint:    lerpC(a.cloudTint,   b.cloudTint),
    oceanColor:   lerpC(a.oceanColor,  b.oceanColor),
    oceanSpec:    lerpC(a.oceanSpec,    b.oceanSpec),
    islandColor:  lerpC(a.islandColor ?? new THREE.Color(0x2d5a27), b.islandColor ?? new THREE.Color(0x2d5a27)),
    rain:         t >= 0.5 ? b.rain : a.rain,
    turbidity:    lerp(a.turbidity ?? 2, b.turbidity ?? 2),
    rayleigh:     lerp(a.rayleigh ?? 1, b.rayleigh ?? 1),
    mieCoefficient: lerp(a.mieCoefficient ?? 0.005, b.mieCoefficient ?? 0.005),
    exposure:     lerp(a.exposure ?? 1, b.exposure ?? 1),
    bloomStrength: lerp(a.bloomStrength ?? 0.4, b.bloomStrength ?? 0.4),
    bloomThreshold: lerp(a.bloomThreshold ?? 0.6, b.bloomThreshold ?? 0.6),
  };
}
